# Generated by Django 3.1.3 on 2021-02-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_grouplesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouplesson',
            name='date',
            field=models.DateField(default='2021-02-18'),
        ),
        migrations.AlterField(
            model_name='grouplesson',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 1), ('COMPLETED', 2), ('NOT_STARTED', 3)], default='NOT_STARTED', max_length=25),
        ),
    ]
