# Generated by Django 3.1.3 on 2021-02-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210220_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplesson',
            name='date',
            field=models.DateField(default='2021-02-18'),
        ),
    ]
