# Generated by Django 3.1.3 on 2021-03-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_grouplesson_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplesson',
            name='notes',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
