# Generated by Django 3.1.3 on 2021-05-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20210327_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('comment', models.CharField(max_length=2500)),
                ('rating', models.IntegerField()),
                ('date', models.DateField(default='2021-05-05')),
            ],
        ),
    ]
