# Generated by Django 3.1.3 on 2021-05-25 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250, null=True)),
                ('date', models.CharField(max_length=250, null=True)),
                ('wished', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StoryReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('date', models.DateField(default='2021-05-05')),
                ('comment', models.CharField(max_length=2500)),
                ('name', models.CharField(max_length=250)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.story')),
            ],
        ),
    ]
