# Generated by Django 3.1.3 on 2021-05-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
