# Generated by Django 3.1.3 on 2021-02-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_signup',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course_signup',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
