# Generated by Django 3.1.3 on 2021-02-07 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('stroke', models.CharField(choices=[('WELLDONE', 1), ('GOODWORK', 2), ('CONGRATULATIONS', 3), ('YOUROCK', 4), ('YOUKILLEDIT', 5), ('YOUNAILEDIT', 6), ('THANKYOU', 7), ('EXCEPTIONAL', 8), ('AMAZING', 9)], max_length=50)),
                ('comments', models.CharField(max_length=250, null=True)),
                ('date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
