# Generated by Django 3.1.3 on 2021-02-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0004_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='student',
            field=models.CharField(max_length=50),
        ),
    ]
