# Generated by Django 3.1.3 on 2021-02-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0005_auto_20210207_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='stroker',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='reward',
            name='stroker_name',
            field=models.CharField(default='Unknown', max_length=15),
        ),
        migrations.AlterField(
            model_name='reward',
            name='stroke',
            field=models.CharField(choices=[('WELLDONE', 1), ('GOODWORK', 2), ('CONGRATULATIONS', 3), ('YOUROCK', 4), ('BRAVO', 5), ('YOUNAILEDIT', 6), ('LOVEIT', 7), ('BRILLIANT', 8), ('AMAZING', 9)], max_length=50),
        ),
    ]
