# Generated by Django 3.1.3 on 2021-02-10 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0006_auto_20210210_0724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='stroker_name',
            new_name='stroker_fname',
        ),
    ]
