# Generated by Django 3.1.3 on 2021-02-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0007_auto_20210210_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystroke',
            name='stroke',
            field=models.CharField(choices=[('WELLDONE', 1), ('GOODWORK', 2), ('CONGRATULATIONS', 3), ('YOUROCK', 4), ('BRAVO', 5), ('YOUNAILEDIT', 6), ('LOVEIT', 7), ('BRILLIANT', 8), ('AMAZING', 9)], max_length=50),
        ),
    ]
