# Generated by Django 3.1.3 on 2021-02-20 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210220_0046'),
        ('rewards', '0009_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stroke', models.CharField(choices=[('WELLDONE', 1), ('GOODWORK', 2), ('CONGRATULATIONS', 3), ('YOUROCK', 4), ('BRAVO', 5), ('YOUNAILEDIT', 6), ('LOVEIT', 7), ('BRILLIANT', 8), ('AMAZING', 9)], max_length=50)),
                ('date', models.DateField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.lesson')),
            ],
        ),
    ]
