# Generated by Django 3.1.3 on 2021-03-12 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rewards', '0012_auto_20210220_0540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25)),
                ('collection', models.CharField(blank=True, max_length=25)),
                ('uri', models.CharField(blank=True, max_length=250)),
                ('ref', models.CharField(blank=True, max_length=250)),
                ('attrib', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserGift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(blank=True, max_length=25)),
                ('gift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rewards.gift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
