# Generated by Django 3.1.3 on 2021-03-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0013_gift_usergift'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='cost',
            field=models.IntegerField(default=10),
        ),
    ]
