# Generated by Django 3.1.3 on 2021-03-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0014_gift_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='attrib',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
