# Generated by Django 3.1.3 on 2021-03-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0015_auto_20210325_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='attrib',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
